### ISSUE TITLE
API performance low

### ISSUE THREAD

**Issue by mkoegel** [klausmeyer/fritzbox-smarthome#37]
Hi Klaus,

I found some time to compare the new reload function with a CURL request.
The reload takes around ~5 seconds.
With cURL it takes only ~1 second.

`curl "http://fritz.box/webservices/homeautoswitch.lua?switchcmd=getdeviceinfos&ain=<ain>&sid=<sid>"`

Not relevant for my use-case, but I thought I let you know as I initially expected the FritzBox to be slow.

-- Michael

**Comment by carpodaster** [comment]
Could be because it looks like every call to the fritz box is re-authenticating. The session id from `Fritzbox::Smarthome::Resource.authenticate` (private singleton method) isn't stateful. If we changed that to instantiating a (e.g.) `Client`  somewhere, the instance could keep track of session expiry and re-authenticate only when required.

**Comment by carpodaster** [comment]
I cannot reproduce the 5 secs locally. With [some modifications](https://github.com/klausmeyer/fritzbox-smarthome/pull/38), I get these results in a log:

```
I, [2022-12-11T13:08:32.764590 #46716]  INFO -- : [HTTParty] [2022-12-11 13:08:32 +0100] 200 "GET https://192.168.178.1/login_sid.lua" - 
I, [2022-12-11T13:08:33.193481 #46716]  INFO -- : [HTTParty] [2022-12-11 13:08:33 +0100] 200 "GET https://192.168.178.1/login_sid.lua?response=REDACTED&username=smarthomeapi" - 
D, [2022-12-11T13:08:33.194665 #46716] DEBUG -- : Request `authentication` took 0.866 seconds
D, [2022-12-11T13:08:33.194775 #46716] DEBUG -- : https://192.168.178.1/webservices/homeautoswitch.lua?switchcmd=getdeviceinfos&sid=REDACTED&ain=13077 0039522-1
I, [2022-12-11T13:08:33.693191 #46716]  INFO -- : [HTTParty] [2022-12-11 13:08:33 +0100] 200 "GET https://192.168.178.1/webservices/homeautoswitch.lua?switchcmd=getdeviceinfos&sid=REDACTED&ain=13077%200039522-1" - 
D, [2022-12-11T13:08:33.693364 #46716] DEBUG -- : Request `https://192.168.178.1/webservices/homeautoswitch.lua?switchcmd=getdeviceinfos&sid=REDACTED&ain=13077 0039522-1` took 0.498 seconds
```

Now I am curious about a proper benchmark (e.g. one that does 100 requests instead of just looking at 2-5 log results), but it looks like the authentication bit takes about twice as long as the other request. Nowhere near 5 seconds for me, though.

From https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_Technical_Note_-_Session_ID.pdf:

> Die Session-ID hat nach Vergabe eine Gültigkeit von 60 Minuten. Die Gültigkeitsdauer
verlängert sich automatisch bei aktivem Zugriff auf die FRITZ!Box.

So if we can keep track of the time of the last call (in a thread variable?), we should be able to drastically improve responsiveness of this Ruby API.

**Comment by klausmeyer** [comment]
Thank you @mkoegel for reporting and @carpodaster for already having a look 🙇 

I'll see when I can have a look myself.

Caching the authentication while it's still valid might be a good idea.

**Comment by mkoegel** [comment]
Thanks for looking into this.
I think keeping the SID might be a good idea.
As per reauthenticating you could either catch the access error or keep a timestamp of the last access.
My job runs every 10 minutes, so the session would never expire.

**Comment by klausmeyer** [comment]
I managed to put something together which caches the authentication.

Maybe you guys could give it a try:

```ruby
# Gemfile
gem 'fritzbox-smarthome', github: 'klausmeyer/fritzbox-smarthome', branch: 'feat/cache-authentication'
```

I did some benchmarks before and after this change for fetching the list of devices 10 times in sequence:

```
# Before
0.157752   0.050965   0.208717 ( 49.320023)
0.156455   0.051065   0.207520 ( 47.343487)
0.156776   0.052967   0.209743 ( 46.295232)

# After
0.113929   0.036594   0.150523 ( 20.608422)
0.113147   0.036387   0.149534 ( 19.637105)
0.111290   0.036473   0.147763 ( 20.883316)
```

**Comment by mkoegel** [comment]
Looks good. This cuts down my reload time from 4-6 seconds to ~1.5 sec.

**Comment by mkoegel** [comment]
I've just made the repository public after finishing some documentation, so you can see what I actually use the gem for.
https://github.com/mkoegel/HeizungsLuefter

**Comment by klausmeyer** [comment]
New release is available now:

* https://github.com/klausmeyer/fritzbox-smarthome/releases/tag/v0.7.0
* https://rubygems.org/gems/fritzbox-smarthome/versions/0.7.0
